### ISSUE TITLE
Global "Add document" sidebar is offset 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-barebones-starter#22]
The global sidebar appears offset from the top of the screen since upgrading to "^0.65.3".
(Maybe this is by design, but it doesn't quite match the media modal that aligns with the top of the screen)

I'm unsure if this is an issue within tinacms, or within this starter.

**Comment by spbyrne** [comment]
By default browsers add 10px of padding to the body element, I suspect that's where this comes from given this starter doesn't have a style reset but I'll take a look.

**Comment by spbyrne** [comment]
Actually that's unrelated; I'll create a pr shortly.

**Comment by spbyrne** [comment]
Fixed here: https://github.com/tinacms/tinacms/pull/2509
