### ISSUE TITLE
The demo's blog post doesn't work

### ISSUE THREAD

**Issue by kslstn** [tinacms/tina-barebones-starter#258]
I installed the starter via:

1. `pnpx create-tina-app@latest`
2. Which package manager would you like to use? › `pnpm`
3.  What is your project named? … `my-tina-app`
4.  What starter code would you like to use? › `Bare bones starter`

I followed the instructions and run `pnpm dev`.

I access the demo on the localhost, navigate to [http://localhost:3000/posts/HelloWorld](http://localhost:3000/posts/HelloWorld) and see a JavaScript object in my browsers viewport (Firefox, Chrome, Safari):

[Home](http://localhost:3000/) | [Posts](http://localhost:3000/posts)
```
{
  "_sys": {
    "filename": "HelloWorld",
    "basename": "HelloWorld.md",
    "breadcrumbs": [
      "HelloWorld"
    ],
    "path": "content/post/HelloWorld.md",
    "relativePath": "HelloWorld.md",
    "extension": ".md"
  },
  "id": "content/post/HelloWorld.md",
  "__typename": "Post",
  "title": "Hello, World!",
  "body": "\nEdit me!\n"
}
```

**Comment by JackDevAU** [comment]
Hi @kslstn 

This is the `barebones starter` as such this is what is expected to be displayed. If you want something a bit more "featured" checkout our other starter [NextJS Starter](https://github.com/tinacms/tina-cloud-starter)

**Comment by kslstn** [comment]
Okay, sure—it may be expected to someone who knows the project. But this may be well be the very first experience of someone trying Tina CMS. To such a person, it doesn't necessarily make sense that the other pages show rendered content, but the post shows raw code. At least to me, a barebones demo offered by the install script not seeming to work consistently makes me lose trust in the Tina project.

Perhaps it should just not be offered by the install script?

**Comment by JackDevAU** [comment]
Hey @kslstn,

You make a great point. The barebones demo is meant to provide a minimal, uncluttered setup, but I agree—the post displaying raw code could definitely be confusing. Do you think it’s worth showing the code, or would you expect the post content to just be rendered instead?

Cheers

**Comment by kslstn** [comment]
As the other pages have rendered content, I expected the post to have it too. But if rendering the object is beyond the intentions of the minimal setup, it could be preceded by text explaining why the code appears. Something like "Your static site generator, UI framework or backend can use the following object to render the post."
